### ISSUE TITLE
Remove need for .cpd.yaml

### ISSUE THREAD

**Issue by lukasoppermann** [yannickcr/gulp-jscpd#1]
Why do I need a .cpd.yaml file? Since I can set the options via an object.

**Comment by yannickcr** [comment]
I suppose you're talking about the `File .cpd.yaml not found in current directory, or it is broken` message.

It is just a warning I did not silenced but the plugin should work with or without a `.cpd.yaml` file.

**Comment by lukasoppermann** [comment]
Exactly, could you silence the warning?

**Comment by binarykitchen** [comment]
Yes, I agree, silence it please

**Comment by sheppy** [comment]
+1

**Comment by shobhit-v** [comment]
+1
