### ISSUE TITLE
Outdated dependencies & node version warning

### ISSUE THREAD

**Issue by ulfryk** [yannickcr/gulp-jscpd#4]
Please update outdated dependencies:

```
$ npm outdated
Package              Current  Wanted  Latest  Location
jscpd                  0.3.6   0.3.6   0.4.0  jscpd
through2               1.1.1   1.1.1   2.0.0  through2
```

`jscpd` seems to be crucial, as version `0.3.6` currently produces warning in newest node:

```
npm WARN engine jscpd@0.3.6: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.7","npm":"2.14.2"})
```

**Comment by ulfryk** [comment]
@yannickcr - is there any chance of updating dependencies ?

**Comment by yannickcr** [comment]
@ulfryk Yes, sorry for the delay. I plan to work on it this week-end.

**Comment by ulfryk** [comment]
@yannickcr - great ! :D

**Comment by ulfryk** [comment]
@yannickcr - thank you very much :+1:
